VisualText/visualtext-files

spec/KBFuncs.nlp
spec/VerticeEdge.nlp

VISUALTEXT-FILES-003 Add vertice & edge functions & KBFunc mods & adds

---

analyzers/english/kb/user/numbers.kb

VISUALTEXT-FILES-004 fixed number.kb

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-006 fixed extra zero for kbb files

---

spec/KBFuncs.nlp

VISUALTEXT-FILE-008 fix DisplayKB to display top level attributes

---

spec/Formatting/RemoveBlankLines.nlp

VISUALTEXT-FILES-009 added missing semicolon

---

spec/Formatting/RemoveBlankLines.nlp
spec/Formatting/RemoveWhiteSpace.nlp
spec/KBFuncs.nlp

VISUALTEXT-FILES-010 changed dictionary functions

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-011 updated Dictionary functions in KBFuncs.nlp

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-013 Fixed AddUniqueStr and AddUniqueNum

---

spec/KBFuncs.nlp

VISUALTEXT-NLP-013 Fixed DictionaryWord

---

Help/helps/NLP_PP_Stuff/Special_Variables.htm

VISUALTEXT-FILES-015 Added help for global variable $islastfile

---

Help/helps/$allcaps.htm
Help/helps/$apppath.htm
Help/helps/$cap.htm
Help/helps/$end.htm
Help/helps/$exists.htm
Help/helps/$input.htm
Help/helps/$inputhead.htm
Help/helps/$inputname.htm
Help/helps/$inputpath.htm
Help/helps/$inputtail.htm
Help/helps/$length.htm
Help/helps/$lowercase.htm
Help/helps/$mixcap.htm
Help/helps/$oend.htm
Help/helps/$ostart.htm
Help/helps/$raw.htm
Help/helps/$start.htm
Help/helps/$text.htm
Help/helps/$treeraw.htm
Help/helps/$treetext.htm
Help/helps/$unknown.htm
Help/helps/$uppercase.htm
Help/helps/$xmltext.htm

VISUALTEXT-FILES-016 Added special variables help files

---

Help/helps/$islastfile.htm

VSCODE-FILES-017 Added $islastfile help file

---

Help/helps/$isfirstfile.htm
Help/helps/NLP_PP_Stuff/Special_Variables.htm

VSCODE-FILES-018 Added $isfirstfile to help

---

Help/helps/$inputparent
Help/helps/$isdirrun
Help/helps/NLP_PP_Stuff/Special_Variables.htm

VSCODE-FILES-019 Added $inputparent and $isdirrun

---

Help/helps/$isdirrun.htm
Help/helps/$isfirstfile.htm
Help/helps/$islastfile.htm
Help/helps/NLP_PP_Stuff/Special_Variables.htm

VISUALTEXT-FILES-021 Fixed some bad cutting and pasting

---

Help/helps/$kbpath.htm
Help/helps/NLP_PP_Stuff/Special_Variables.htm

VISUALTEXT-FILES-022 added $kbpath help

---

Help/helps/$anaspath.htm
Help/helps/NLP_PP_Stuff/Special_Variables.htm

VISUALTEXT-FILES-025 Added anaspath

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-026 Added new KB function PathToConcept

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-027 Fixed DisplayKB

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-028 added display type 2 for compact without ellipses

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-029 Fixing double quotes in DisplayKB

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-030 Added PadStr

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-031 Fixed double square bracket bug

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-032 Fixing DisplayKB AGAIN!

---

Help/helps/Table_of_Knowledge_Base_Functions.htm
Help/helps/Table_of_Parse_Tree_Functions.htm
Help/helps/attrtype.htm
Help/helps/pncopyvars.htm

VISUALTEXT-FILES-034 Added attrtype and updated pncopyvars to include concepts

---

Help/helps/Table_of_Knowledge_Base_Functions.htm
Help/helps/getconval.htm
Help/helps/getfltval.htm
Help/helps/getnumval.htm
Help/helps/getstrval.htm
spec/KBFuncs.nlp

VISUALTEXT-FILES-035 KBDisplay function updates and new help

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-036 Fixing DisplayKB

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-037 DisplayKB bug

---

spec/KBFuncs.nlp

VISUALTEXT-FILES-038 new SaveKB in KBFuncs.nlp

---

analyzers/Address Parser/README.md
analyzers/Email Addresses/README.md
analyzers/Telephone Numbers/README.md
analyzers/URLs/README.md

Updated the readme of analyzers

Readme for Analyzers
